/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RentnChillRouteImport } from './routes/RentnChill'
import { Route as ExcursionsRouteImport } from './routes/Excursions'
import { Route as ContactUsRouteImport } from './routes/ContactUs'
import { Route as AwardsRouteImport } from './routes/Awards'
import { Route as IndexRouteImport } from './routes/index'

const RentnChillRoute = RentnChillRouteImport.update({
  id: '/RentnChill',
  path: '/RentnChill',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcursionsRoute = ExcursionsRouteImport.update({
  id: '/Excursions',
  path: '/Excursions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/ContactUs',
  path: '/ContactUs',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/Awards',
  path: '/Awards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Awards': typeof AwardsRoute
  '/ContactUs': typeof ContactUsRoute
  '/Excursions': typeof ExcursionsRoute
  '/RentnChill': typeof RentnChillRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Awards': typeof AwardsRoute
  '/ContactUs': typeof ContactUsRoute
  '/Excursions': typeof ExcursionsRoute
  '/RentnChill': typeof RentnChillRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Awards': typeof AwardsRoute
  '/ContactUs': typeof ContactUsRoute
  '/Excursions': typeof ExcursionsRoute
  '/RentnChill': typeof RentnChillRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Awards' | '/ContactUs' | '/Excursions' | '/RentnChill'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Awards' | '/ContactUs' | '/Excursions' | '/RentnChill'
  id:
    | '__root__'
    | '/'
    | '/Awards'
    | '/ContactUs'
    | '/Excursions'
    | '/RentnChill'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AwardsRoute: typeof AwardsRoute
  ContactUsRoute: typeof ContactUsRoute
  ExcursionsRoute: typeof ExcursionsRoute
  RentnChillRoute: typeof RentnChillRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/RentnChill': {
      id: '/RentnChill'
      path: '/RentnChill'
      fullPath: '/RentnChill'
      preLoaderRoute: typeof RentnChillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Excursions': {
      id: '/Excursions'
      path: '/Excursions'
      fullPath: '/Excursions'
      preLoaderRoute: typeof ExcursionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ContactUs': {
      id: '/ContactUs'
      path: '/ContactUs'
      fullPath: '/ContactUs'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Awards': {
      id: '/Awards'
      path: '/Awards'
      fullPath: '/Awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AwardsRoute: AwardsRoute,
  ContactUsRoute: ContactUsRoute,
  ExcursionsRoute: ExcursionsRoute,
  RentnChillRoute: RentnChillRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
